package main

import (
	"context"

	"github.com/Aliizi83/vohu/config"
	"github.com/Aliizi83/vohu/internal/platform/agenttool"
	"github.com/Aliizi83/vohu/internal/platform/auth"
	"github.com/Aliizi83/vohu/internal/platform/chat"
	"github.com/Aliizi83/vohu/internal/platform/conversation"
	"github.com/Aliizi83/vohu/internal/platform/custommodel"
	"github.com/Aliizi83/vohu/internal/platform/httpserver"
	"github.com/Aliizi83/vohu/internal/platform/migrations"
	"github.com/Aliizi83/vohu/internal/platform/providerkey"
	"github.com/Aliizi83/vohu/internal/platform/rbac"
	"github.com/Aliizi83/vohu/internal/platform/sshconn"
	"github.com/Aliizi83/vohu/internal/platform/user"
	"github.com/Aliizi83/vohu/internal/tools/command"
	"github.com/Aliizi83/vohu/pkg/crypto"
	"github.com/Aliizi83/vohu/pkg/db"
	"github.com/Aliizi83/vohu/pkg/logging"

	// Side-effect import — registers this build's generated spec with
	// swag's internal registry; ginSwagger.WrapHandler reads it from
	// there, not from this package's exports directly. Regenerated by
	// `swag init` (see Makefile-less equivalent: the command in docs.go's
	// own header comment) whenever a handler's annotations change.
	_ "github.com/Aliizi83/vohu/docs"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title			Vohu Platform API
// @version		1.0
// @description	HTTP API for Vohu's multi-user platform — users, roles, polymorphic resource access, SSH connections, conversations/chat, provider keys, custom models, and the agent tool catalog. Every endpoint responds through shared.BaseResponse (see internal/platform/shared/response.go) — {result, success, resultCode, validationErrors, error} — regardless of success or failure.
// @BasePath		/api/v1
//
// @securityDefinitions.apikey	BearerAuth
// @in							header
// @name						Authorization
// @description				Type "Bearer" followed by a space and the access token from POST /auth/login or /auth/refresh.
func main() {
	cfg := config.GetConfig()
	logger := logging.NewLogger(cfg)

	if err := db.InitDB(cfg); err != nil {
		logger.Fatal(err, logging.Postgres, logging.Startup, err.Error(), nil)
	}
	defer db.CloseDB()

	if err := migrations.UpP_1(db.GetDB(), logger); err != nil {
		logger.Fatal(err, logging.Postgres, logging.Migration, err.Error(), nil)
	}

	rbacRepo := rbac.NewRepository(db.GetDB())
	rbacService := rbac.NewService(rbacRepo)
	rbacHandler := rbac.NewHandler(rbacService)

	// rbac.AccessLevel/ResourceEffect are named string types; every other
	// module's injected checks/hooks take plain strings so no module but
	// this one ever has to import rbac just to bridge the two.
	hasAccessLevel := func(ctx context.Context, userID uint, resourceType string, resourceID uint, level string) (bool, error) {
		return rbacService.HasAccessLevel(ctx, userID, resourceType, resourceID, rbac.AccessLevel(level))
	}
	grantCreatorAccess := func(ctx context.Context, userID uint, resourceType string, resourceID uint, level string, effect string) error {
		return rbacService.GrantResourceAccess(
			ctx, rbac.GranteeUser, userID, resourceType, resourceID, rbac.AccessLevel(level), rbac.ResourceEffect(effect),
		)
	}

	userRepo := user.NewRepository(db.GetDB())
	userService := user.NewService(userRepo, hasAccessLevel)
	userHandler := user.NewHandler(userService)

	secretBox, err := crypto.NewBox(cfg.Secrets.EncryptionKey)
	if err != nil {
		logger.Fatal(err, logging.General, logging.Startup, err.Error(), nil)
	}

	// TestConnectionFunc lives in internal/tools/command (the package that
	// already owns every SSH-dialing concern) so sshconn itself never
	// imports it directly — same injected-function pattern as
	// grantCreatorAccess/hasAccessLevel above.
	testSSHConnection := command.TestDial

	sshconnRepo := sshconn.NewRepository(db.GetDB())
	sshconnService := sshconn.NewService(sshconnRepo, secretBox, grantCreatorAccess, hasAccessLevel, testSSHConnection)
	sshconnHandler := sshconn.NewHandler(sshconnService)

	authService := auth.NewService(cfg, userService)
	authHandler := auth.NewHandler(authService)

	conversationRepo := conversation.NewRepository(db.GetDB())
	conversationService := conversation.NewService(conversationRepo, hasAccessLevel)

	// Same allow-list the "command:*" keys used to describe under the old
	// flat-permission system — pwd/ls/whoami/git status/git log/docker
	// ps/docker logs — applied to every SSH connection for now (nothing
	// per-connection yet). Accept-mode (allow-list), unlike cmd/vohu's own
	// TESTING-ONLY deny-list, since this runs unattended against
	// user-supplied remote hosts rather than a developer's own machine.
	sshCommandPolicy := command.NewCommandPolicy(command.PolicyModeAccept, []command.Rule{
		{Program: "pwd", Allowed: true},
		{Program: "ls", Allowed: true},
		{Program: "whoami", Allowed: true},
		{Program: "git", ArgsPrefixes: [][]string{{"status"}, {"log"}}, Allowed: true},
		{Program: "docker", ArgsPrefixes: [][]string{{"ps"}, {"logs"}}, Allowed: true},
	})
	providerKeyRepo := providerkey.NewRepository(db.GetDB())
	providerKeyService := providerkey.NewService(providerKeyRepo, secretBox)
	providerKeyHandler := providerkey.NewHandler(providerKeyService)

	customModelRepo := custommodel.NewRepository(db.GetDB())
	customModelService := custommodel.NewService(customModelRepo, secretBox)
	customModelHandler := custommodel.NewHandler(customModelService)

	agentToolRepo := agenttool.NewRepository(db.GetDB())
	agentToolService := agenttool.NewService(agentToolRepo, hasAccessLevel)
	agentToolHandler := agenttool.NewHandler(agentToolService)

	chatHandler := chat.NewHandler(
		conversationService, sshconnService, hasAccessLevel, sshCommandPolicy, providerKeyService, customModelService, agentToolService,
	)

	engine, v1 := httpserver.NewEngine(logger)

	// /swagger/index.html — no auth: it's documentation, not data: every
	// documented endpoint still enforces its own auth/access checks
	// exactly as before regardless of who can view the spec.
	engine.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	authMiddleware := authService.Authentication()

	user.RegisterRoutes(v1, userHandler, authMiddleware, hasAccessLevel)
	rbac.RegisterRoutes(v1, rbacHandler, authMiddleware, rbacService)
	sshconn.RegisterRoutes(v1, sshconnHandler, authMiddleware, hasAccessLevel)
	providerkey.RegisterRoutes(v1, providerKeyHandler, authMiddleware, hasAccessLevel)
	custommodel.RegisterRoutes(v1, customModelHandler, authMiddleware, hasAccessLevel)
	agenttool.RegisterRoutes(v1, agentToolHandler, authMiddleware, hasAccessLevel)
	chat.RegisterRoutes(v1, chatHandler, authMiddleware)
	auth.RegisterRoutes(v1, authHandler)

	logger.Info(logging.General, logging.Startup, "starting vohu server", nil)

	if err := httpserver.Run(engine, cfg); err != nil {
		logger.Fatal(err, logging.General, logging.Startup, err.Error(), nil)
	}
}
